name: Build libmobile for ios
on:
  workflow_dispatch:
  workflow_call:

jobs:
  ios_libmobile:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          export PATH="/Users/piss/tools/ldc2-1.35.0-osx-arm64/bin/:$PATH"
          which ldc2
          make DC=ldc2 PLATFORM=arm64-apple-ios libmobile
          file ./build/arm64-apple-ios/lib/libmobile.dylib

      - name: Check output binaries
        run: |
          ! nm build/arm64-apple-ios/lib/libmobile.dylib | grep __dyld_get_image_slide

      - uses: actions/upload-artifact@v3
        if: success()
        with:
          name: libmobile
          path: ./build/*/lib/libmobile.dylib
          if-no-files-found: error

      - name: Cleanup
        run: |
          make PLATFORM=arm64-apple-ios clean
