name: Unittest and Nightly build
on:
  workflow_dispatch:
  push: 
    branches: 
      - current
env:
  ## Sets environment variable
  TARGET_BUILD: x86_64-linux
  PARALEL: 1
  RETENTION_DAYS_BINS: 3
  TAGION_CACHE_DIR: ~/tagion_cache 
  RUN_SCENARIOUS_PARALEL: true
  ## TODO: add ldc2/dmd switch & version
jobs:
  build_and_unittest:
    runs-on: self-hosted
    steps:
      - name: Cleanup
        run: |
          sudo rm -rf *
          sudo rm -rf .git
          sudo rm -rf .github
          sudo rm -rf .vscode
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cache of libs
        run: |
          if [ -d ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }} ]; then
            echo "Copying cache"
            mkdir -p ./build/${{ env.TARGET_BUILD }}
            ls ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD}}/
            cp -fr ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD}}/* ./build/${{ env.TARGET_BUILD }}/
            ls ./build/${{ env.TARGET_BUILD }}/
          else 
            echo "Cache not found"
          fi
      - name: Run unittests
        run: |
          source ~/.bashrc
          make unittest -j ${{ env.PARALEL }}
      - name: Upload unittest result
        uses: actions/upload-artifact@v3
        with:
          name: core-unittests-logs
          path: logs/${{ env.TARGET_BUILD }}/unittest.log

      - name: Check unittests
        run: cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep -E "^[0-9]+ modules passed unittests"

      - name: Report unittests
        if: success()
        run: |
          RESULT=$(cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep -E "^[0-9]+ modules passed unittests")
          echo -e "### :heavy_check_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY
      - name: Report unittests
        if: failure()
        run: |
          RESULT=$(cat logs/${{ env.TARGET_BUILD }}/unittest.log | grep FAILED)
          echo -e "### :heavy_exclamation_mark: Unittests passed \n $RESULT" >> $GITHUB_STEP_SUMMARY


      - name: Run Bdd tests
        run: |
          source ~/.bashrc
          make bddtest TEST_STAGE=commit | tail -n 3 | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' > bddconsole.log

      - name: Create bdd result
        run: |
          for i in ./logs/${{ env.TARGET_BUILD }}/bdd/results/*.json; do cat $i | jq '.info.name,.info.result.outcome."$@",.info.result.outcome.msg?'; done  | sed 'N;N;s/\n/ - /g' |  tr -d '"' | sed s/"- null"// > ./bddresult.log
      
      - name: Report Bdd result
        run: |
          cat ./bddresult.log >> $GITHUB_STEP_SUMMARY

      - name: Upload Bdd result
        uses: actions/upload-artifact@v3
        with:
          name: core-bdd-logs
          path: logs/${{ env.TARGET_BUILD }}/bdd/

      - name: Check bdd result
        run: cat ./bddconsole.log | tail -n 1 | grep -E "Test result success!"

      - name: Build
        run: |
          source ~/.bashrc
          make tagion -j ${{ env.PARALEL }}
          
      - name: Upload bins
        uses: actions/upload-artifact@v3
        with:
          name: core-bins
          path: build/${{ env.TARGET_BUILD }}/bin/tagion
          retention-days: ${{ env.RETENTION_DAYS_BINS }}
      
      - name: Create passed tag
        if: success() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "passed"
          force_push_tag: true

      - name: Create failed tag
        if: failure() && (github.ref == 'refs/heads/current')
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "failed"
          force_push_tag: true


      - name: Make cache of libs
        run: |
          ls
          DIFF=$(diff --speed-large-files --recursive --brief ./build/${{ env.TARGET_BUILD}}/tmp ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}/tmp)
          DIFF+=$(diff --speed-large-files --recursive --brief ./build/${{ env.TARGET_BUILD }}/lib ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}/lib)
          if [ "$DIFF" != "" ] ; then
            sudo rm -rf ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}
            sudo mkdir -p ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}
            sudo /bin/cp -rf ./build/${{ env.TARGET_BUILD}}/tmp ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}/
            sudo /bin/cp -rf ./build/${{ env.TARGET_BUILD }}/lib ${{ env.TAGION_CACHE_DIR }}/${{ env.TARGET_BUILD }}/
          fi
