name: Design Review

on:
  schedule:
    - cron: '42 15 * * 0' # Every Sunday at 17:42 CEST
  workflow_dispatch:

env:
  shipit:  https://i.shipit.today

jobs:
  create_pull_request:
    runs-on: CI
    steps:
      - uses: actions/checkout@v3
      - name: Get week number
        id: week-number
        run: echo "::set-output name=week::$(date +'%U')"
      
      - name: Create Pull Request
        run: |
          export GH_TOKEN=${{ env.GITBOT_TOKEN }}
          export RAND=$(echo $((RANDOM % 59 +1)))
          gh pr create --title "Review week ${{ steps.week-number.outputs.week }}" \
                       --body "Changes to be reviewed for week: ${{ steps.week-number.outputs.week }}   \
                       ![LGTM](${{ env.shipit }}/$RAND)" \
                       --base master --head current
