name: Test Tagionwave

on: 
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Artifact run id'
        required: false
        type: number
      clean:
        description: 'Reset network bills'
        required: true
        default: true
        type: boolean
      wallets:
        description: 'How many wallets'
        required: true
        type: number
        default: 5
      nodes:
        description: 'Amount of nodes'
        required: true
        type: number
        default: 5
          #      mode:
          #        description: 'Network Mode'
          #        required: true
          #        default: 'INTERNAL'
          #        type: choice
          #        options:
          #          - INTERNAL
          #          - LOCAL
          #          - PUB
          #      environment:
          #        description: 'Environment to run tests against'
          #        type: environment
          #        required: true

jobs:
  deploy_tagionwave:
    runs-on: testnet
    environment: 
      name: testnet-mobile
      url: http://10.210.2.10:8080

    steps:
      - name: get artifact
        run: |
          rm -rf *
          loginctl enable-linger moonbase
          gh run download ${{ inputs.artifact_run_id }} -n successful_artifact --repo tagion/tagion
          tar -xzf *.tar.gz

      - name: Backup old data
        if: ${{ inputs.clean }}
        run: |
          DIR_EPOCH=$(stat -c%W ~/.local/share/tagion) && \
          # OLD_DIR_NAME=~/.local/share/tagion_$(date -d @$DIR_EPOCH +%F_%H-%M) && \
          # mv ~/.local/share/tagion $OLD_DIR_NAME || \
          # echo "No old data to backup"
          cd ~/.local/share/
          OLD_TAR_NAME=tagion_$(date -d @$DIR_EPOCH +%F_%H-%M).tar.gz && \
            tar czf $OLD_TAR_NAME tagion/ && \
            rm -r tagion || \
            echo "No old data to backup"

      - name: Create new bills
        if: ${{ inputs.clean }}
        run: |
          cd build/x86_64-linux/bin
          ./tagion -s
          ./create_wallets_2.sh -b $PWD -k ~/.local/share/tagion/wave -t ~/.local/share/tagion/wallets -w ${{ inputs.wallets }} -n ${{ inputs.nodes }}

      - name: start service
        run: |
          cd build/x86_64-linux/bin
          export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
          export XDG_RUNTIME_DIR=/run/user/1001
          systemctl stop --user neuewelle.service | echo "No wave service was running"
          systemctl stop --user tagionshell.service | echo "No shell service was running"
          mkdir -p ~/.local/share/bin
          mkdir -p ~/.config/systemd/user
          cp tagion ~/.local/share/bin/
          echo "Deploying revision" >> $GITHUB_STEP_SUMMARY
          ~/.local/share/bin/tagion --version >> $GITHUB_STEP_SUMMARY
          cp tagionshell.service neuewelle.service ~/.config/systemd/user
          systemctl --user daemon-reload
          systemctl restart --user neuewelle.service
          systemctl restart --user tagionshell.service
